name: CML
on: [push]
jobs:
  launch-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: Deploy runner on AWS EC2
        # Supports AWS, Azure, GCP, K8s
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          cml runner launch \
          --cloud=aws \
          --cloud-region=us-west \
          --cloud-type=m5.2xlarge \
          --labels=cml-runner
  train-and-report:
    runs-on: [self-hosted, cml-runner]
    needs: launch-runner
    timeout-minutes: 50400 # 35 days
    container: docker://iterativeai/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Train model
        run: |
          pip install -r requirements.txt
          python train.py  # generate plot.png
          echo "## Report from your EC2 Instance" >> report.md
          cat metrics.txt >> report.md
          echo '![](./plot.png "Confusion Matrix")' >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}